### ISSUE TITLE
关于版权风险

### ISSUE THREAD

**Issue by star7th** [Beipy/BeipyVideoResolution#5]
首先说下，我是不打算用你的程序来二次打包盈利的。我只是想技术研究。
但我看了下你的代码，似乎只是一个壳，并没有解析的部分。我原本还想着看代码学习下怎么解析人家的网址，可能也没办法了。
不过我还是来提醒一下你版权风险。虽然说你提醒了视频版权归原作者所有。但破解了人家的VIP视频，并以盈利为目的出售或者投放广告，是已经涉及到盗版侵权了的。因为你盈利了，所以不能算技术研究的范畴了，是商业侵权了。人家正规的视频网站如果要告你，是百分百能赢的。而且，由于涉及到了盈利，你可能还需要做出赔偿甚至坐牢。你声明了什么都不能免责的。所以建议不要为了赚钱把事情弄大，低调赚点小费好了。
当然这只是我一点看法。你按照你想法去做就好。

**Comment by PasserbyFluid** [comment]
说的很对啊  现在还有很多加壳的app那种也是解析视频的 说爱我

**Comment by Koukotsukan** [comment]
详见破解抖音国际版被抓坐牢的20岁酷安小伙

**Comment by Beipy** [comment]
我只是做的一个壳子，并没有涉及任何核心破解。另外也未曾打算使用源码盈利。

**Comment by Koukotsukan** [comment]
> 我只是做的一个壳子，并没有涉及任何核心破解。另外也未曾打算使用源码盈利。

是的，这的确不是问题

**Comment by star7th** [comment]
都把VIP视频破解了，哪叫”不涉及到任何核心破解“。无论是你破解还是利用什么谁制作的什么工具，你都是重要的传播者之一。至于说不盈利，你敢当天发誓你没有因这个项目有一分钱的收入吗？捐赠也属于盈利，以及利用此项目带来的关注度二次盈利（如广告）也是盈利。

**Comment by star7th** [comment]
我已经把话说得很清楚了。你这种辩解在法律面前是毫无说服力的。不想再多说。
